[package]
name = "rush"
version = "0.3.0"
edition = "2018"
authors = ["Cardinal Cryptography"]
categories = ["algorithms", "data-structures", "cryptography", "database"]
documentation = "https://docs.rs/?"
homepage = "https://alephzero.org"
repository = "https://github.com/cardinal-cryptography/?"
keywords = ["aleph", "asynchronous", "consensus", "bft", "blockchain", "distributed-systems"]
license = "Apache-2.0"
readme = "README.md"

description = """
    Aleph is an asynchronous and Byzantine fault tolerant consensus protocol aimed
    at ordering arbitrary messages (transactions). It has been designed to operate
    continuously under conditions where there is no bound on message-delivery delay
    and under the assumption that there is a significant probability of malicious
    behavior, making it an excellent fit for blockchain-related applications.
    """

[dependencies]
bit-vec = "0.6"
futures = "0.3"
derive_more = "0.99"
log = "0.4"
rand = "0.8"
async-trait = "0.1"

tokio = { version = "0.2.21", features = ["macros", "time"] }
codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive"] }

[dev-dependencies]
libp2p = { version ="0.38", features = ["mdns", "tcp-tokio"]}
tokio = { version = "0.2.21", features = ["macros", "rt-threaded", "time"] }
parking_lot = "0.11"
env_logger = "0.8"
