[package]
name = "rush"
version = "0.1.0"
authors = ["Michal Swietek <michal.swietek@cardinals.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.11.1"
futures = "0.3.9"
tokio = { version = "1.5.0", features = ["macros", "rt-threaded", "sync", "time"] }
mini-redis = "0.4"
derive_more = "0.99.7"
serde = { version = "1.0.110", features = ["derive"] }
futures-timer = "3.0.2"
log = "0.4.14"
env_logger = "0.8.3"
codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive"] }
rand = "0.8.3"
